version: "3.3"
services:
    server-becd9691-b958-47c3-9ac3-688ca48fb6d6:
        image: hotstuff-erasure
        command: ["100", "25", "1000"]
        hostname: server
        cap_add:
            - NET_ADMIN
        labels:
            becd9691-b958-47c3-9ac3-688ca48fb6d6: "true"
        deploy:
            replicas: 4
            endpoint_mode: dnsrr
        environment:
            ERASURE_UUID: "becd9691-b958-47c3-9ac3-688ca48fb6d6"
        networks:
            - ErasureNet

networks:
    ErasureNet:
        external:
            name: erasure_network
    outside:
        driver: overlay
