version: "3.3"
services:
    server-hecd9691-b958-47c3-9ac3-688ca48fb6d6:
        image: hotchunk
        command: ["master", "50", "100", "1000", "5000"]
        hostname: server
        cap_add:
            - NET_ADMIN
        labels:
            hecd9691-b958-47c3-9ac3-688ca48fb6d6: "true"
        deploy:
            replicas: 20
            endpoint_mode: dnsrr
        environment:
            ERASURE_UUID: "hecd9691-b958-47c3-9ac3-688ca48fb6d6"
        networks:
            - ErasureNet

networks:
    ErasureNet:
        external:
            name: erasure_network
    outside:
        driver: overlay
